name: First Workflow

on:
  push:
    branches:
      - master
      - dev
      - 'releases/**'

jobs:
  example-job:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo Hello, World!
        run: echo "Hello, World!"